### ISSUE TITLE
Міша всьо хуйня, давай по новой 

### ISSUE THREAD

**Issue by seriusokhatsky** [ernest35/pure_2.0#1]
:)

**Comment by misha-pelykh** [comment]
:+1:

**Comment by seriusokhatsky** [comment]
https://www.youtube.com/watch?v=B-jQfN3n7tc&feature=youtu.be&t=83

**Comment by misha-pelykh** [comment]
https://www.youtube.com/watch?v=B-jQfN3n7tc&feature=youtu.be&t=242
